spring:
  application:
    name: zuul

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

zuul:
  routes:
    client:
      path: /client/**
      serviceId: client

